# Generated by Django 3.2.4 on 2021-07-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='city_name',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
