# Generated by Django 3.2.4 on 2021-07-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210705_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city_name',
            field=models.IntegerField(choices=[(0, 'Raleigh'), (1, 'Durham'), (2, 'Cary'), (3, 'Morrisville'), (4, 'Apex'), (5, 'Garner')], default=0),
        ),
    ]
