# Generated by Django 3.2.5 on 2021-07-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210714_0231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scrapuser',
            unique_together={('email', 'username')},
        ),
    ]
