# Generated by Django 3.2.4 on 2021-07-09 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210709_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapuser',
            name='post',
        ),
        migrations.AddField(
            model_name='scrapuser',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
