# Generated by Django 3.2.4 on 2021-07-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city_name',
            field=models.CharField(choices=[(0, 'Raleigh'), (1, 'Durham'), (2, 'Cary'), (3, 'Morrisville'), (4, 'Apex'), (5, 'Garner')], default=0, max_length=100),
        ),
    ]
