# Generated by Django 3.2.5 on 2021-07-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_scrapuser_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scrapuser',
            unique_together={('email',)},
        ),
    ]
