# Generated by Django 3.2.4 on 2021-07-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210709_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapuser',
            name='post',
        ),
        migrations.AddField(
            model_name='scrapuser',
            name='post',
            field=models.ManyToManyField(null=True, to='posts.Post'),
        ),
    ]
