# Generated by Django 3.2.4 on 2021-07-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210709_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapuser',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Post'),
        ),
    ]
