# Generated by Django 3.2.4 on 2021-07-09 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_scrapuser_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapuser',
            name='post',
        ),
        migrations.AddField(
            model_name='scrapuser',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
