# Generated by Django 3.2.4 on 2021-07-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210709_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapuser',
            name='saved',
            field=models.ManyToManyField(null=True, related_name='blog_post', to='posts.Post'),
        ),
    ]
