# Generated by Django 3.2.4 on 2021-07-10 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_scrapuser_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapuser',
            name='saved',
        ),
        migrations.AddField(
            model_name='post',
            name='saved',
            field=models.ManyToManyField(null=True, related_name='add_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
