# Generated by Django 3.2.4 on 2021-07-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210728_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city_name',
            field=models.IntegerField(choices=[(0, 'Raleigh'), (1, 'Durham'), (2, 'Cary'), (3, 'Morrisville'), (4, 'Apex'), (5, 'Garner')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/<function user_directory_path at 0x7fe2c48e5b80>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/<function user_directory_path at 0x7fe2c48e5b80>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/<function user_directory_path at 0x7fe2c48e5b80>'),
        ),
    ]
