# Generated by Django 3.2.5 on 2021-07-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20210729_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/<function user_directory_path at 0x7fb08f218ee0>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/<function user_directory_path at 0x7fb08f218ee0>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/<function user_directory_path at 0x7fb08f218ee0>'),
        ),
        migrations.AlterField(
            model_name='scrapuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_pic/<function user_profilepic_path at 0x7fb08fd84160>'),
        ),
    ]
