# Generated by Django 3.2.5 on 2021-07-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20210729_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'other')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/<function user_directory_path at 0x7f940edf30d0>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/<function user_directory_path at 0x7f940edf30d0>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/<function user_directory_path at 0x7f940edf30d0>'),
        ),
    ]
