# Generated by Django 3.2.5 on 2021-07-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20210730_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_count',
            field=models.ManyToManyField(null=True, related_name='post_count', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/<function user_directory_path at 0x7fe17a0cfa60>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/<function user_directory_path at 0x7fe17a0cfa60>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/<function user_directory_path at 0x7fe17a0cfa60>'),
        ),
    ]
